### ISSUE TITLE
Backup phrase can't be confirmed

### ISSUE THREAD

**Issue by 634-5789** [Blockstream/aqua_ios#2] opened 2020-10-26 13:38 UTC
I received a screenshot of someone I recommended Aqua. The person tried to make a new wallet and was stuck at the confirmation page. The screenshot didn't make any sense to me, too. 

I attached it and censored the words. It looks like the phrases "Which is word No. 5" or anything similar was missing.

https://imgur.com/a/v9JmAX0

**Comment by bstin** [comment] 2020-10-30 18:45
Hi @634-5789 

This looks to be a duplicate of the issue I opened here: https://github.com/Blockstream/aqua_ios/issues/1

**Comment by 634-5789** [comment] 2020-10-30 18:49
It is, sorry didn't see it. I'll close this one.

**Closed** 2020-10-30 18:49 UTC
